#! /usr/bin/env bash

BASE_DIR=../../test_data/hadam3p_eu_ins0_1985_1_008476005_0
EU_FILE=$BASE_DIR/ins0ga.pdi5dec.nc
N_PTS=0
LEV=7
EX_LEV=7
T_STEP=$1
N_STEPS=120
PLT_LEV=$2

GRID_FILE=../../grids/eu_mesh_$N_PTS"_"$LEV".msh"
RGD_FILE=${EU_FILE%.nc}_l$LEV"".rgd
EX_FILE=${EU_FILE%.nc}_l$EX_LEV"".ex
OUT_FILE=${EU_FILE%.nc}_"$PLT_LEV"_"$T_STEP".png

cmd="../plot_tri_tracker.py -m $GRID_FILE -o $OUT_FILE -l $PLT_LEV -t $T_STEP -s $N_STEPS -x [-15.5,39.0] -y [28.5,72.0] -p 198 -q 39.25 -e $EX_FILE -r $RGD_FILE"
echo $cmd
$cmd
