#! /usr/bin/env bash
BASE_PATH=/Volumes/MacintoshHD2/shared/WaH_Data/OSTIA_ins0/
INS0_DIR=$BASE_PATH/1985/hadam3p_eu_ins0_1985_1_008476005_0
EU_FILE=$INS0_DIR/ins0ga.pdi6jan.nc
WND_FILE=$EU_FILE

T_STEP=$1
LEV=7
PLT_LEV=7
EX_LEV=7
PERIM=4
N_PTS=0
IT=$2

RGD_FILE=${EU_FILE%.nc}_l$LEV"".rgd

GRID_FILE=../../grids/eu_mesh_N$N_PTS"_L"$LEV"_P"$PERIM".msh"
OUT_FILE=${EU_FILE%.nc}_l$LEV""_t$T_STEP"it_"$IT".eps"
EX_FILE=${EU_FILE%.nc}_l$EX_LEV"it_"$IT".ex"

LIMITS="-x [-14.0,27.0] -y [47.0,73.0]"
#LIMITS="-x [-15.5,39.0] -y [28.5,72.0]"
#cmd="../plot_tri_tracker.py -m $GRID_FILE -r $RGD_FILE -e $EX_FILE -o $OUT_FILE -l $PLT_LEV -t $T_STEP -x [-15.5,39.0] -y [28.5,72.0] -p 198.0 -q 39.25"
cmd="../plot_tri_tracker.py -m $GRID_FILE -e $EX_FILE -o $OUT_FILE -l $PLT_LEV -t $T_STEP $LIMITS -p 198.0 -q 39.25"
echo $cmd
$cmd
