#!/usr/bin/env python

###############################################################################
# Program : print_metadata.py
# Author  : Neil Massey
# Date    : 30/04/15
# Purpose : Program to print the metadata from the files generated by tritracker
###############################################################################

import sys,getopt
from meta_data import *

###############################################################################

if __name__ == "__main__":
    input = ""
    opts, args = getopt.getopt(sys.argv[1:], 'i:', ['input='])

    for opt, val in opts:
        if opt in ['--input', '-i']:
            input = val
            
    fh = open(input, 'rb')
    md = read_meta_data(fh)
    
    for k in md:
        print k + " : " + md[k]
    fh.close()