#!/usr/bin/env bash
# test the global version

EU_FILE=/Users/massey/WaH/output/EU/hadam3p_eu_p3at_2011_1_008287381_1/p3atma.pcl1dec.nc
N_PTS=1
LEV=5
GRID_FILE=grids/global_mesh_$N_PTS"_"$LEV
NC_VAR=field8_1
GP_VAR=field1
RGD_FILE=${EU_FILE%.nc}_l$LEV"".rgd
EX_FILE=${EU_FILE%.nc}_l$LEV"".ex
NC_RE_FILE=$RGD_FILE"_2D0".nc
TRK_FILE=${EU_FILE%.nc}_l$LEV"".trk
DEG=2.0
EX_ARGS='minima(101300,0,12,0.0000)'
TRK_WTS=" -0 1.0 -1 49.36 -2 5.54 -3 35.0 "
TRK_ARGS="-r 1000 -p 1 -d 0 -l 0 -t 1 -k 1 -s 0 "

# generate a grid
#echo ./gen_grid_reg -f $EU_FILE -v $NC_VAR -o $GRID_FILE -n $N_PTS -I 10 -l $LEV -L
#./gen_grid_reg -f $EU_FILE -v $NC_VAR -o $GRID_FILE -n $N_PTS -I 10 -l $LEV -L
# regrid the netCDF file
#echo ./regrid_reg -i $EU_FILE -v $NC_VAR -m $GRID_FILE -o $RGD_FILE -T
#./regrid_reg -i $EU_FILE -v $NC_VAR -m $GRID_FILE -o $RGD_FILE -T
# convert back to netCDF file
#echo ./tri_grid_to_netcdf -i $RGD_FILE -m $GRID_FILE -v $NC_VAR -o $NC_RE_FILE -l $LEV -s $DEG -t $DEG
#./tri_grid_to_netcdf -i $RGD_FILE -m $GRID_FILE -v $NC_VAR -o $NC_RE_FILE -l $LEV -s $DEG -t $DEG
# locate extrema
#echo ./extrema_reg -i $RGD_FILE -o $EX_FILE -m $GRID_FILE -l $LEV --method $EX_ARGS -T
#./extrema_reg -i $RGD_FILE -o $EX_FILE -m $GRID_FILE -l $LEV --method $EX_ARGS -T
# locate tracks
echo ./track_reg -i $EX_FILE -o $TRK_FILE $TRK_WTS $TRK_ARGS -T
./track_reg -i $EX_FILE -o $TRK_FILE $TRK_WTS $TRK_ARGS -T
