#!/usr/bin/env bash
BASE_PATH=/Volumes/MacintoshHD2/shared/WaH_Data/OSTIA_ins0/
INS0_DIR=$BASE_PATH/1985/hadam3p_eu_ins0_1985_1_008476005_0
EU_FILE=$INS0_DIR/ins0ga.pdi6jan.nc
WND_FILE=$EU_FILE
GP_FILE=$EU_FILE
N_PTS=0
LEV=7
EX_LEV=7
PERIM=4
IT=5
GRID_FILE=../grids/eu_mesh_N$N_PTS"_L"$LEV"_P"$PERIM".msh"
EXE_PATH=../exe
NC_VAR=field8
WND_VAR=field50
LSM_FILE=/Volumes/MacintoshHD2/LSM/wah_eu_lsm_0_44_pos_lonlat.nc
RGD_FILE=${EU_FILE%.nc}_l$LEV"".rgd
OUT_FILE=${EU_FILE%.nc}_l$LEV"".png
EX_FILE=${EU_FILE%.nc}_l$EX_LEV"it_"$IT".ex"
EV_FILE=$INS0_DIR/ins0ga.pdi
TRK_FILE=${EU_FILE%.nc}_l$LEV"".trk
BCK_FIELD="$BASE_PATH/back_ens/ens_mean_ins0_1985_dec.rgd"
EX_ARGS='minima_back_wind('$BCK_FIELD',5,1,5,200.0,1000.0,'$WND_FILE','$WND_VAR',5.495520385,9.508252308)'
GP_ARGS='geostrophic('$GP_FILE',field1,0)'
TRK_WTS=" -0 1.0 -1 49.36 -2 5.54 -3 35.0 "
TRK_ARGS="-r 1000 -p 1 -d 0 -l 0 -t 1 -k 1 -s 0 -T"

# generate a grid
#cmd="$EXE_PATH/gen_grid -f $EU_FILE -v $NC_VAR -o $GRID_FILE -n $N_PTS -I 0 -l $LEV -p $PERIM"
#echo $cmd
#$cmd

# regrid the netCDF file
#cmd="$EXE_PATH/regrid -i $EU_FILE -v $NC_VAR -m $GRID_FILE -o $RGD_FILE -S 0.07"
#echo $cmd
#$cmd

# locate the extrema
cmd="$EXE_PATH/extrema -i $RGD_FILE -o $EX_FILE -m $GRID_FILE -l $EX_LEV --method $EX_ARGS --steering $GP_ARGS"
echo $cmd
$cmd

# build an event set from the extrema
# can pass in multiple files like with the tracking
EX_FILES="$INS0_DIR/ins0ga.pdi5dec_l7.ex -i $INS0_DIR/ins0ga.pdi6jan_l7.ex -i $INS0_DIR/ins0ga.pdi6feb_l7.ex -i $INS0_DIR/ins0ga.pdi6mar_l7.ex"
EU_FILES="$INS0_DIR/ins0ga.pdi5dec.nc -m $INS0_DIR/ins0ga.pdi6jan.nc -m $INS0_DIR/ins0ga.pdi6feb.nc -m $INS0_DIR/ins0ga.pdi6mar.nc"
WND_FILES="$INS0_DIR/ins0ga.pdi5dec.nc -w $INS0_DIR/ins0ga.pdi6jan.nc -w $INS0_DIR/ins0ga.pdi6feb.nc -w $INS0_DIR/ins0ga.pdi6mar.nc"

# short versions
#EX_FILES="$INS0_DIR/ins0ga.pdi5dec_l7.ex -i $INS0_DIR/ins0ga.pdi6jan_l7.ex"
#EU_FILES="$INS0_DIR/ins0ga.pdi5dec.nc -m $INS0_DIR/ins0ga.pdi6jan.nc"
#WND_FILES="$INS0_DIR/ins0ga.pdi5dec.nc -w $INS0_DIR/ins0ga.pdi6jan.nc"

EV_72HR_DIR=$INS0_DIR"/events_72hr"
EV_TV_DIR=$INS0_DIR"/events_timevar" 

if [ ! -e $EV_72HR_DIR ]; then
	mkdir $EV_72HR_DIR
fi

if [ ! -e $EV_TV_DIR ]; then
	mkdir $EV_TV_DIR
fi

#cmd="$EXE_PATH/event_set -i $EX_FILES -o $EV_FILE -p 6 -d 0.0 -l 0.0 -r 1000.0 -t 12 -v 10 -m "$EU_FILES" -w "$WND_FILES" -s "$LSM_FILE" -g "$GRID_FILE
#echo $cmd
#$cmd

#cmd="mv $INS0_DIR"/*_72h.csv" $EV_72HR_DIR"
#$cmd
#cmd="mv $INS0_DIR"/*_tv.csv" $EV_TV_DIR"
#$cmd

# track the extrema
#cmd="$EXE_PATH/track -i $EX_FILE -o $TRK_FILE $TRK_WTS $TRK_ARGS"
#echo $cmd
#$cmd
