#!/usr/bin/env bash
# test the global version

EU_FILE=../test_data/wah_m001ma_1960/m001ma.pbg1dec.nc
LEV=5
GRID_FILE=../grids/global_mesh_l""$LEV".msh"
NC_VAR=field8
GP_VAR=field1
RGD_FILE=${EU_FILE%.nc}_l$LEV"".rgd
EX_FILE=${EU_FILE%.nc}_l$LEV"".ex
TRK_FILE=${EU_FILE%.nc}_l$LEV"".trk

# gunzip source file
gunzip $EU_FILE".gz"
# create grids directory if it doesn't exist
if [ ! -e ../grids ]; then
    mkdir ../grids
fi
# generate a grid
cmd="../exe/gen_grid -f $EU_FILE -v $NC_VAR -o $GRID_FILE -I 100 -l $LEV -L"
echo $cmd
$cmd

# regrid the netCDF file
#echo ./regrid_reg -i $EU_FILE -v $NC_VAR -m $GRID_FILE -o $RGD_FILE -T
#./regrid_reg -i $EU_FILE -v $NC_VAR -m $GRID_FILE -o $RGD_FILE -T
# gzip the file back
gzip $EU_FILE
# convert back to netCDF file
#echo ./tri_grid_to_netcdf -i $RGD_FILE -m $GRID_FILE -v $NC_VAR -o $NC_RE_FILE -l $LEV -s $DEG -t $DEG
#./tri_grid_to_netcdf -i $RGD_FILE -m $GRID_FILE -v $NC_VAR -o $NC_RE_FILE -l $LEV -s $DEG -t $DEG
# locate extrema
#echo ./extrema_reg -i $RGD_FILE -o $EX_FILE -m $GRID_FILE -l $LEV --method $EX_ARGS -T
#./extrema_reg -i $RGD_FILE -o $EX_FILE -m $GRID_FILE -l $LEV --method $EX_ARGS -T
# locate tracks
#echo ./track_reg -i $EX_FILE -o $TRK_FILE $TRK_WTS $TRK_ARGS -T
#./track_reg -i $EX_FILE -o $TRK_FILE $TRK_WTS $TRK_ARGS -T
