#!/usr/bin/env bash
INS0_DIR=/Volumes/MacintoshHD2/WaH_Data/OSTIA_ins0/1986/hadam3p_eu_j7u7_1986_1_008502004_0
EU_FILE=$INS0_DIR/j7u7ga.pdi6dec.nc
N_PTS=0
LEV=7
EX_LEV=7
PERIM=4
GRID_FILE=../grids/eu_mesh_N$N_PTS"_L"$LEV"_P"$PERIM".msh"
EXE_PATH=../exe
NC_VAR=field8
RGD_FILE=${EU_FILE%.nc}_l$LEV"".rgd
OUT_FILE=${EU_FILE%.nc}_l$LEV"".png
EX_FILE=${EU_FILE%.nc}_l$EX_LEV"".ex
TRK_FILE=${EU_FILE%.nc}_l$LEV"".trk
#EX_ARGS='minima(101300,0,12,0.0000)'
WND_FIELD=
BCK_FIELD="/Volumes/MacintoshHD2/WaH_Data/OSTIA_ins0/back_clim/clim_1985_2011_dec.rgd"
EX_ARGS='minima_back_wind('$BCK_FIELD',4,1,4,200.0,400.0,'$EU_FILE',field50)'
GP_ARGS='geostrophic('$EU_FILE',field8,0)'
TRK_WTS=" -0 1.0 -1 49.36 -2 5.54 -3 35.0 "
TRK_ARGS="-r 1000 -p 1 -d 0 -l 0 -t 1 -k 1 -s 0 "

# generate a grid
cmd="$EXE_PATH/gen_grid -f $EU_FILE -v $NC_VAR -o $GRID_FILE -n $N_PTS -I 0 -l $LEV -p $PERIM"
echo $cmd
$cmd

# regrid the netCDF file
cmd="$EXE_PATH/regrid -i $EU_FILE -v $NC_VAR -m $GRID_FILE -o $RGD_FILE -S 0.07"
echo $cmd
$cmd

# locate the extrema
cmd="$EXE_PATH/extrema -i $RGD_FILE -o $EX_FILE -m $GRID_FILE -l $EX_LEV --method $EX_ARGS"
echo $cmd
$cmd

# track the extrema
#cmd="$EXE_PATH/track -i $EX_FILE -o $TRK_FILE $TRK_WTS $TRK_ARGS"
#echo $cmd
#$cmd
